format_version: v1.0
type: GeneratorComponent
attributes: {id: usb_device_hid}
children:
- type: Instances
  children:
  - type: InstanceComponent
    attributes: {instance: '0', id: usb_device_hid}
    children:
    - type: Symbols
      children:
      - type: Integer
        attributes: {id: CONFIG_USB_DEVICE_FUNCTION_INTERFACE_NUMBER}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: usb_device_hid_0, value: '0'}
      - type: Integer
        attributes: {id: CONFIG_USB_DEVICE_FUNCTION_INT_IN_ENDPOINT_NUMBER}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: usb_device_hid_0, value: '1'}
      - type: Integer
        attributes: {id: CONFIG_USB_DEVICE_FUNCTION_INT_OUT_ENDPOINT_NUMBER}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: usb_device_hid_0, value: '1'}
      - type: Combo
        attributes: {id: CONFIG_USB_DEVICE_HID_REPORT_DESCRIPTOR_TYPE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: usb_device_hid_bootloader, value: Custom}
    - type: Attachments
      children:
      - type: DirectCapability
        attributes: {id: USB Device}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: targetComponentID}
            children:
            - {type: Value, value: usb_device_hid_bootloader}
          - type: String
            attributes: {id: targetAttachmentID}
            children:
            - {type: Value, value: btl_USB_DEVICE_HID_dependency}
- type: ElementPosition
  attributes: {x: '168', y: '216', id: usb_device_hid}
